### PR TITLE
Ported DH code from crypticl.

### PR DESCRIPTION
**Pull request by shrdlu68**
I've tested it on SBCL but it's ANSI CL so the test should work anywhere.

### CODE REVIEW

**Comment by glv2** [comment]
Hi.

There is already a pull request (PR #71) containing functions for Diffie-Hellman key exchanges for multiplicative groups of integers modulo a prime (elgamal) and for some elliptic curves (curve25519 and curve448).

Also, the functions for modular exponentiation and random integer generation are already in the *math.lisp* file.

**Comment by shrdlu68** [comment]
Hello,
there does not seem to be an API for performing a Diffie-Hellman key-exchange (as used in TLS in the ServerKeyExchange message and ClientKeyExchange message). If ironclad does indeed support this, I would gladly use the its implementation because that it what I am after anyway. I may also be needing Ironclad's ECC implementation for DHE and ECDSA soon. It seems additions have been made to ironclad but the documentation has not been updated yet, because I ported the DH code from crypticl thinking ironclad does not have support for DH key exchange.

**Comment by glv2** [comment]
The current release of ironclad doesn't have the DH key exchange code because PR #71 has not been merged into the main branch of the code yet.

In PR #71, the function to perform DH key exchange with integers modulo a prime is in the *elgamal.lisp* file because the format of the key pairs for DH key exchange and Elgamal encryption is exactly the same (but we could create a new key pair class just for DH if that is confusing).

**Comment by shrdlu68** [comment]
Ah, I see. math.lisp contains all that's needed anyway to implement it anyway, no need to import code from another project. I may make a pull request with the DH key exchange API (this time using code already in ironclad) if and when #71 is merged.

**Pull request closed without merging**
